//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBakeryWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderId { get; set; }
        public string OrderDate { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Pay_Type { get; set; }
        public int Product_Id { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual TableProduct TableProduct { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
