//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBakeryWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableProduct()
        {
            this.OrderTables = new HashSet<OrderTable>();
        }
    
        public int PId { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public Nullable<int> PCategoryId { get; set; }
        public string PDescription { get; set; }
        public Nullable<int> FreeDelivery { get; set; }
        public Nullable<int> COD { get; set; }
        public string PIMAGE { get; set; }
    
        public virtual TableCategory TableCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
    }
}
