//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBakeryWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProductImage
    {
        public int PimgId { get; set; }
        public Nullable<int> PID { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
    }
}
