//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBakeryWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineBakeryEntities : DbContext
    {
        public OnlineBakeryEntities()
            : base("name=OnlineBakeryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableCategory> TableCategories { get; set; }
        public virtual DbSet<TableProduct> TableProducts { get; set; }
        public virtual DbSet<TableProductImage> TableProductImages { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<OrderConfirmTable> OrderConfirmTables { get; set; }
        public virtual DbSet<OrderTable> OrderTables { get; set; }
    }
}
